### ISSUE TITLE
fatal: not a git repository when running `nxt ui`

### ISSUE THREAD

**Issue by johhnry** [nxt-dev/nxt_editor#130]
Hi,

**Describe the bug**
This is the output when I run the editor : 

```
$ nxt ui
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**To Reproduce**
1. Install `nxt` with `pip install nxt-editor`
2. Run the editor : `nxt ui`

**Expected behavior**
I should not see any errors.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.10
 - Version 3.5.1, API v0.9.1, Graph v1.17

Why is it checking if there's a git repository?

**Comment by ImLucasBrown** [comment]
You can safely ignore this error. We'll have it fixed in the next release.


Its from bit of code used for internal debugging, it sets the window title to the current git branch. There was a time at Sunrise when everyone was running NXT from a clone and we needed a quick way to know what branch they had checked out.

**Comment by johhnry** [comment]
Hi,

Thanks for the quick feedback!

Have a nice day
